$activeBorderColor = rgb(d4a85a)
$inactiveBorderColor = rgb(1e4040)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
